version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8509:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11439:11434"
    volumes:
      - ./models/.ollama:/root/.ollama
      - .:app/
